{
 "title": "Bitcoin exporter (Raw data)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Current status of nodes",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(bitcoin_blocks) by (job,instance,chain,currency,syncmode)"
    },
    {
     "expr": "sum(bitcoin_size_on_disk) by (job,instance)"
    },
    {
     "expr": "sum(bitcoin_connections) by (job,instance)"
    },
    {
     "expr": "sum(bitcoin_errors:sum) by (job,instance)"
    },
    {
     "expr": "sum(bitcoin_up) by (job,instance)"
    },
    {
     "expr": "sum(bitcoin_subversion) by (job,instance,value)"
    },
    {
     "expr": "sum(bitcoin_ready) by (job,instance)"
    }
   ]
  },
  {
   "title": "Memory pool state",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(bitcoin_txcount) by(job,instance,currency,chain,syncmode)"
    },
    {
     "expr": "sum(bitcoin_txrate) by(job,instance,currency,chain,syncmode)"
    },
    {
     "expr": "sum(bitcoin_mempoolsize) by(job,instance,currency,chain,syncmode)"
    },
    {
     "expr": "sum(bitcoin_mempoolbytes) by(job,instance,currency,chain,syncmode)"
    },
    {
     "expr": "sum(bitcoin_mempoolusage) by(job,instance,currency,chain,syncmode)"
    },
    {
     "expr": "sum(bitcoin_maxmempool) by(job,instance,currency,chain,syncmode)"
    }
   ]
  },
  {
   "title": "Other stats",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(bitcoin_time) by (job,instance,chain,currency) * 1000"
    },
    {
     "expr": "sum(bitcoin_mediantime) by (job,instance,chain,currency) * 1000"
    },
    {
     "expr": "sum(bitcoin_pruned) by (job,instance,chain,currency)"
    }
   ]
  },
  {
   "title": "Bitcoin nodes errors rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none", "label": "Count/sec" }
   ],
   "targets": [
    { "expr": "rate(bitcoin_errors:sum[5m])", "legendFormat": "{{ job }}" }
   ]
  }
 ]
}