name: 'PR Checks'
on: [pull_request, push]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: 'Check Yarn installed'
        run: yarn --version

      - name: 'Install dependencies...'
        run: yarn install
