name: 'Test workflow'
on: [push]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: 12.8.x

      - name: 'Install dependencies'
        run: yarn

      - name: 'Check with ESLint'
        run: eslint src
