name: Test workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.8.x, 12.9.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          yarn install
      - name: Check syntax
        run: |
          yarn eslint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Login to docker registry
        run: docker login -u ${DOCKER_LOGIN} -p ${DOCKER_PASSWORD}
        env:
          DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --pull -t ${IMAGE}:${TAG}
        env:
          IMAGE: 4ops/bitcoin-exporter
          TAG: test

      - name: Publish the Docker image
        run: docker push ${IMAGE}:${TAG}
        env:
          IMAGE: 4ops/bitcoin-exporter
          TAG: test
