name: 'Test workflow'
on: [push]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: 12.8.x

      - name: 'Check nodejs version'
        run: node --version

      - name: 'Check Yarn installed'
        run: yarn --version

      - name: 'Install dependencies...'
        run: yarn install
