#
# Use this resource only if prometheus operator installed.
# See: https://github.com/coreos/prometheus-operator
#
# It's just an example! Edit this file before deploy to kubernetes cluster!
#
apiVersion: v1
kind: Service
metadata:
  labels:
    chain: test
    currency: bch
    syncmode: txindex
    api-metrics: bitcoin-exporter
  name: bch-test-txindex-nodes
  namespace: testing
spec:
  ports:
    - name: api-metrics
      port: 9133
      protocol: TCP
      targetPort: 9133
  selector:
    chain: test
    currency: bch
    syncmode: txindex
  sessionAffinity: None
  type: ClusterIP
  clusterIP: None
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blockchain-api-metrics
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      port: api-metrics
      path: /metrics
      scheme: http
      scrapeTimeout: 5s
  namespaceSelector:
    matchNames:
      - testing
  selector:
    matchLabels:
      api-metrics: bitcoin-exporter
  targetLabels:
    - chain
    - currency
    - syncmode
